version: 2.1
jobs:
  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - run: |
          aws cloudformation create-stack --stack-name DemoBGDeployment --region $AWS_DEFAULT_REGION --template-body file://template.yml 
workflows:
  cloudformation-deployment:
    jobs:
      - create_infrastructure