version: 2.1
jobs:
  # create_infrastructure:
  #   docker: 
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run: pwd
  #     - run: ls -alh
  #     - run: |
  #         aws cloudformation create-stack --stack-name DemoBGDeployment --region $AWS_DEFAULT_REGION --template-body file://template.yml 
  execute_ansible_playbook:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "64:d5:f1:45:24:78:e0:e8:5d:5e:f9:87:26:98:ea:1b"
      - run: ansible-playbook main-remote.yml -i inventory
    
  workflows:
  cloudformation-deployment:
    jobs:
      # - create_infrastructure
      - execute_ansible_playbook